<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
df.price

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [4]:
type(df.price)

pandas.core.series.Series

In [5]:
df[['area']]

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [6]:
type(df[['area']])

pandas.core.frame.DataFrame

In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

C:\Users\Raghu Prasad\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [11]:
import pickle

In [12]:
with open('model_pickle_may_2023','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [13]:
with open('model_pickle_may_2023','rb') as file:
    mp = pickle.load(file)

In [14]:
mp.coef_

array([135.78767123])

In [15]:
mp.intercept_

180616.43835616432

In [16]:
mp.predict([[5000]])

C:\Users\Raghu Prasad\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [17]:
#from sklearn.externals import joblib
import joblib

In [18]:
joblib.dump(model, 'model_joblib_march_2021')

['model_joblib_march_2021']

<h4 style='color:purple'>Load Saved Model</h4>

In [19]:
mj = joblib.load('model_joblib_march_2021')

In [20]:
mj.coef_

array([135.78767123])

In [21]:
mj.intercept_

180616.43835616432

In [22]:
mj.predict([[5000]])

C:\Users\Raghu Prasad\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])